### ISSUE TITLE
x86 xtask build is broken

### ISSUE THREAD

**Issue by ColinLeftwich** [Caznix/IneptOS#2]
Cargo xtask run/build x86_84 fails to build. It gives the error "No such file or directory" when trying to find the built binary located in kernel/target/x86_64-unknown-none/debug

**Comment by ColinLeftwich** [comment]
@Caznix I checked PathBuf and that wasn't the issue, turns out the target directory is no longer located in kernel so it wasn't finding the build binary. This should fix it.

**Comment by tristanpoland** [comment]
Can confirm this is still an issue, I will work on it this afternoon if I have some time.
